// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2Eat.Infrastructure;

#nullable disable

namespace _2Eat.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517201645_AddForslagIngredientNames")]
    partial class AddForslagIngredientNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergenIngredient", b =>
                {
                    b.Property<int>("AllergensId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.HasKey("AllergensId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("AllergenIngredient");

                    b.HasData(
                        new
                        {
                            AllergensId = 0,
                            IngredientsId = 1
                        });
                });

            modelBuilder.Entity("AllergenRecipe", b =>
                {
                    b.Property<int>("AllergensId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipesId")
                        .HasColumnType("integer");

                    b.HasKey("AllergensId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("AllergenRecipe");
                });

            modelBuilder.Entity("_2Eat.Domain.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 0
                        },
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDinnerEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDinnerEligible = false,
                            Name = "Bakverk"
                        },
                        new
                        {
                            Id = 2,
                            IsDinnerEligible = true,
                            Name = "Smörgåsar"
                        },
                        new
                        {
                            Id = 3,
                            IsDinnerEligible = true,
                            Name = "Kött"
                        },
                        new
                        {
                            Id = 4,
                            IsDinnerEligible = true,
                            Name = "Fisk"
                        },
                        new
                        {
                            Id = 5,
                            IsDinnerEligible = true,
                            Name = "Övrigt"
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.Files.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("_2Eat.Domain.Forslag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SourceSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAt");

                    b.HasIndex("SourceSite");

                    b.ToTable("Forslag");
                });

            modelBuilder.Entity("_2Eat.Domain.ForslagIngredientName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForslagId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ForslagId");

                    b.ToTable("ForslagIngredientNames");
                });

            modelBuilder.Entity("_2Eat.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Vetemjöl"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Name = "Strösocker"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Name = "Ägg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Name = "Smör"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Name = "Mjölk"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Name = "Grädde"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Name = "Potatis"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Lax"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Dill"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Name = "Rödbetor"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Räkor"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Name = "Kavring"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Name = "Västerbottensost"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Renkött"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Name = "Lingon"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Name = "Kanel"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Name = "Kardemumma"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Name = "Älgkött"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Surströmming"
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.IngredientMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IngredientMeasurements");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlanDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealPlanDays");
                });

            modelBuilder.Entity("_2Eat.Domain.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsLow")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("_2Eat.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CookTime")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("Fat")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("integer");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("_2Eat.Domain.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientMeasurementId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("IngredientMeasurementId")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("_2Eat.Domain.Samling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Samlingar");
                });

            modelBuilder.Entity("_2Eat.Domain.SamlingRecept", b =>
                {
                    b.Property<int>("SamlingId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceptId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("SamlingId", "ReceptId");

                    b.HasIndex("ReceptId");

                    b.HasIndex("SamlingId");

                    b.ToTable("SamlingarRecept");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("_2Eat.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShoppingListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ShoppingListId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_2Eat.Domain.UserForslag", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ForslagId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ForslagId");

                    b.HasIndex("ForslagId");

                    b.HasIndex("UserId");

                    b.ToTable("UserForslag");
                });

            modelBuilder.Entity("AllergenIngredient", b =>
                {
                    b.HasOne("_2Eat.Domain.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllergenRecipe", b =>
                {
                    b.HasOne("_2Eat.Domain.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.ForslagIngredientName", b =>
                {
                    b.HasOne("_2Eat.Domain.Forslag", null)
                        .WithMany("IngredientNames")
                        .HasForeignKey("ForslagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.Ingredient", b =>
                {
                    b.HasOne("_2Eat.Domain.Category", "Category")
                        .WithMany("Ingredients")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlan", b =>
                {
                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlanDay", b =>
                {
                    b.HasOne("_2Eat.Domain.MealPlan", "MealPlan")
                        .WithMany("Days")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("_2Eat.Domain.PantryItem", b =>
                {
                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.Recipe", b =>
                {
                    b.HasOne("_2Eat.Domain.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_2Eat.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("_2Eat.Domain.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.IngredientMeasurement", "IngredientMeasurement")
                        .WithOne()
                        .HasForeignKey("_2Eat.Domain.RecipeIngredient", "IngredientMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("IngredientMeasurement");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("_2Eat.Domain.Samling", b =>
                {
                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.SamlingRecept", b =>
                {
                    b.HasOne("_2Eat.Domain.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.Samling", "Samling")
                        .WithMany("Recept")
                        .HasForeignKey("SamlingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Samling");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("_2Eat.Domain.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("_2Eat.Domain.User", b =>
                {
                    b.HasOne("_2Eat.Domain.ShoppingList", "ShoppingList")
                        .WithOne("User")
                        .HasForeignKey("_2Eat.Domain.User", "ShoppingListId");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("_2Eat.Domain.UserForslag", b =>
                {
                    b.HasOne("_2Eat.Domain.Forslag", "Forslag")
                        .WithMany()
                        .HasForeignKey("ForslagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forslag");
                });

            modelBuilder.Entity("_2Eat.Domain.Category", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("_2Eat.Domain.Forslag", b =>
                {
                    b.Navigation("IngredientNames");
                });

            modelBuilder.Entity("_2Eat.Domain.Ingredient", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("_2Eat.Domain.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("_2Eat.Domain.Samling", b =>
                {
                    b.Navigation("Recept");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
