// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _2Eat.Infrastructure;

#nullable disable

namespace _2Eat.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512190631_AddDesserterCategory")]
    partial class AddDesserterCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergenIngredient", b =>
                {
                    b.Property<int>("AllergensId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.HasKey("AllergensId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("AllergenIngredient");

                    b.HasData(
                        new
                        {
                            AllergensId = 0,
                            IngredientsId = 1
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 0
                        },
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bakverk"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smörgåsar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kött"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fisk"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Övrigt"
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.Files.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("_2Eat.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Vetemjöl"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Name = "Strösocker"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Name = "Ägg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Name = "Smör"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Name = "Mjölk"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Name = "Grädde"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Name = "Potatis"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Lax"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Dill"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Name = "Rödbetor"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Räkor"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Name = "Kavring"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Name = "Västerbottensost"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Renkött"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Name = "Lingon"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Name = "Kanel"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Name = "Kardemumma"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Name = "Älgkött"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Name = "Surströmming"
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.IngredientMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IngredientMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 500.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 250.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 200.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 4,
                            Quantity = 3.0,
                            Unit = 9
                        },
                        new
                        {
                            Id = 5,
                            Quantity = 100.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 6,
                            Quantity = 250.0,
                            Unit = 1
                        },
                        new
                        {
                            Id = 7,
                            Quantity = 200.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 8,
                            Quantity = 2.0,
                            Unit = 9
                        },
                        new
                        {
                            Id = 9,
                            Quantity = 50.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 10,
                            Quantity = 1.0,
                            Unit = 2
                        },
                        new
                        {
                            Id = 11,
                            Quantity = 500.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 12,
                            Quantity = 100.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 13,
                            Quantity = 400.0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 14,
                            Quantity = 200.0,
                            Unit = 1
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlanDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanDays");
                });

            modelBuilder.Entity("_2Eat.Domain.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsLow")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("_2Eat.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CookTime")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CookTime = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 12, 19, 6, 30, 807, DateTimeKind.Unspecified).AddTicks(8061), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Traditionella svenska kanelbullar",
                            Difficulty = "Medel",
                            Instructions = "Blanda ingredienser och baka i 180°C i 15 minuter.",
                            LastModified = new DateTimeOffset(new DateTime(2021, 10, 10, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Kanelbullar",
                            PrepTime = 45,
                            Rating = 5,
                            Servings = 4
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CookTime = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 12, 19, 6, 30, 807, DateTimeKind.Unspecified).AddTicks(9660), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "En klassisk svensk räkmacka",
                            Difficulty = "Medel",
                            Instructions = "Montera mackan med bröd, räkor, majonnäs och dill.",
                            LastModified = new DateTimeOffset(new DateTime(2021, 10, 10, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Räkmacka",
                            PrepTime = 10,
                            Rating = 4,
                            Servings = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CookTime = 120,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 12, 19, 6, 30, 807, DateTimeKind.Unspecified).AddTicks(9665), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Älgstek med enbär",
                            Difficulty = "Medel",
                            Instructions = "Rosta älgköttet med enbär och servera med potatis och lingon.",
                            LastModified = new DateTimeOffset(new DateTime(2023, 10, 10, 15, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Älgstek",
                            PrepTime = 30,
                            Rating = 5,
                            Servings = 6
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CookTime = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 12, 19, 6, 30, 807, DateTimeKind.Unspecified).AddTicks(9667), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Lax i en krämig sås",
                            Difficulty = "Medel",
                            Instructions = "Laga laxen i en gräddig sås med dill och servera med kokt potatis.",
                            LastModified = new DateTimeOffset(new DateTime(2024, 10, 10, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Lax med grädde",
                            PrepTime = 20,
                            Rating = 4,
                            Servings = 4
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientMeasurementId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("IngredientMeasurementId")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            Id = 1,
                            IngredientMeasurementId = 1,
                            Order = 0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 17,
                            Id = 2,
                            IngredientMeasurementId = 2,
                            Order = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            Id = 3,
                            IngredientMeasurementId = 3,
                            Order = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            Id = 4,
                            IngredientMeasurementId = 4,
                            Order = 3
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            Id = 5,
                            IngredientMeasurementId = 5,
                            Order = 4
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            Id = 6,
                            IngredientMeasurementId = 6,
                            Order = 5
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 12,
                            Id = 7,
                            IngredientMeasurementId = 7,
                            Order = 0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 13,
                            Id = 8,
                            IngredientMeasurementId = 8,
                            Order = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 9,
                            Id = 9,
                            IngredientMeasurementId = 9,
                            Order = 2
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 19,
                            Id = 10,
                            IngredientMeasurementId = 10,
                            Order = 0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 7,
                            Id = 11,
                            IngredientMeasurementId = 11,
                            Order = 1
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 16,
                            Id = 12,
                            IngredientMeasurementId = 12,
                            Order = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 8,
                            Id = 13,
                            IngredientMeasurementId = 13,
                            Order = 0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 6,
                            Id = 14,
                            IngredientMeasurementId = 14,
                            Order = 1
                        });
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("_2Eat.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShoppingListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ShoppingListId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AllergenIngredient", b =>
                {
                    b.HasOne("_2Eat.Domain.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.Ingredient", b =>
                {
                    b.HasOne("_2Eat.Domain.Category", "Category")
                        .WithMany("Ingredients")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlan", b =>
                {
                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlanDay", b =>
                {
                    b.HasOne("_2Eat.Domain.MealPlan", "MealPlan")
                        .WithMany("Days")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("_2Eat.Domain.PantryItem", b =>
                {
                    b.HasOne("_2Eat.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2Eat.Domain.Recipe", b =>
                {
                    b.HasOne("_2Eat.Domain.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_2Eat.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("_2Eat.Domain.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.IngredientMeasurement", "IngredientMeasurement")
                        .WithOne()
                        .HasForeignKey("_2Eat.Domain.RecipeIngredient", "IngredientMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Eat.Domain.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("IngredientMeasurement");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("_2Eat.Domain.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("_2Eat.Domain.User", b =>
                {
                    b.HasOne("_2Eat.Domain.ShoppingList", "ShoppingList")
                        .WithOne("User")
                        .HasForeignKey("_2Eat.Domain.User", "ShoppingListId");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("_2Eat.Domain.Category", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("_2Eat.Domain.Ingredient", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("_2Eat.Domain.MealPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("_2Eat.Domain.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("_2Eat.Domain.ShoppingList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
